# This workflow will do a will make issues from todos comments in my project

name: Making Issues From Todos

on:
    push:
        branches: ["master"]

jobs:
    check-todos:
        runs-on: ubuntu-latest

        steps:
            - name: Verifying Repository
              uses: actions/checkout@v3
            - name: Todo to Issue
              uses: alstr/todo-to-issue-action@v4
              with:
                  AUTO_ASSIGN: true
